title: My Jekyll Site

url: https://faenuccio-teaching.github.io
baseurl: "/GradCourse26"
repository: faenuccio-teaching/GradCourse26/pages

# remote_theme: pages-themes/cayman@v0.2.0
remote_theme: pages-themes/minimal@v0.2.0
#
plugins:
  - jekyll-remote-theme
  - jekyll-github-metadata
