title: ""
description: ""
url: https://faenuccio-teaching.github.io
baseurl: "/GradCourse26"
repository: faenuccio-teaching/GradCourse26
layout: default
nav_enabled: false

remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

keep_files:
  - docs
  - docbuild

show_downloads: true

